import { onCall, onRequest } from 'firebase-functions/v2/https';
import { adminDb } from './shared/admin.js';
import { requireAdmin, requireAuthenticatedUid, resolveAuthenticatedActor } from './auth/actor.js';
import { AppError, toHttpsError } from './shared/errors.js';
import { FirestorePaymentRepository } from './payments/payment.repository.js';
import { PaymentService } from './payments/payment.service.js';
import { PaymentPromiseService } from './invoices/payment-promise.service.js';
import { MERCADO_PAGO_ACCESS_TOKEN, MERCADO_PAGO_ORDERS_ACCESS_TOKEN, MERCADO_PAGO_ORDERS_WEBHOOK_SECRET } from './config/payment-config.js';
import { PixPaymentService } from './payments/pix-payment.service.js';
import { isMercadoPagoOrderEvent } from './payments/webhook-event.js';

const paymentService = new PaymentService(new FirestorePaymentRepository(adminDb));
const promiseService = new PaymentPromiseService(adminDb);
const loadMercadoPagoProvider = () => import('./payments/providers/mercado-pago.provider.js');
const loadWebhookService = () => import('./payments/webhook.service.js');

export const createPaymentIntent = onCall({ region: 'southamerica-east1' }, async request => { try { const actor = await resolveAuthenticatedActor(adminDb, requireAuthenticatedUid(request.auth)); return await paymentService.createIntent(actor, request.data); } catch (error) { throw toHttpsError(error); } });
export const requestPaymentPromise = onCall({ region: 'southamerica-east1' }, async request => { try { const actor = await resolveAuthenticatedActor(adminDb, requireAuthenticatedUid(request.auth)); return await promiseService.request(actor, request.data); } catch (error) { throw toHttpsError(error); } });
export const createPixPayment = onCall({ region: 'southamerica-east1', secrets: [MERCADO_PAGO_ORDERS_ACCESS_TOKEN] }, async request => { try { const actor = await resolveAuthenticatedActor(adminDb, requireAuthenticatedUid(request.auth)); const repository = new FirestorePaymentRepository(adminDb); const { MercadoPagoProvider } = await loadMercadoPagoProvider(); return await new PixPaymentService(adminDb, repository, new MercadoPagoProvider(MERCADO_PAGO_ORDERS_ACCESS_TOKEN.value())).create(actor, request.data); } catch (error) { throw toHttpsError(error); } });
export const reconcilePayment = onCall({ region: 'southamerica-east1', secrets: [MERCADO_PAGO_ORDERS_ACCESS_TOKEN, MERCADO_PAGO_ACCESS_TOKEN] }, async request => { try { const [{ MercadoPagoProvider }, { PaymentWebhookService }] = await Promise.all([loadMercadoPagoProvider(), loadWebhookService()]); const actor = requireAdmin(await resolveAuthenticatedActor(adminDb, requireAuthenticatedUid(request.auth))); const paymentId = request.data?.paymentId; if (typeof paymentId !== 'string' || !/^[a-zA-Z0-9_-]{1,128}$/.test(paymentId)) throw new AppError('invalid-argument', 'Pagamento inválido.'); const result = await new PaymentWebhookService(adminDb, new MercadoPagoProvider(MERCADO_PAGO_ORDERS_ACCESS_TOKEN.value(), MERCADO_PAGO_ACCESS_TOKEN.value())).reconcile(paymentId, `reconcile:${actor.uid}:${paymentId}`); return { paymentId, result }; } catch (error) { throw toHttpsError(error); } });
export const mercadoPagoWebhook = onRequest({ region: 'southamerica-east1', secrets: [MERCADO_PAGO_ORDERS_ACCESS_TOKEN, MERCADO_PAGO_ORDERS_WEBHOOK_SECRET], timeoutSeconds: 30 }, async (request, response) => { if (request.method !== 'POST') { response.status(405).send('method-not-allowed'); return; } if (!isMercadoPagoOrderEvent(request.body)) { response.status(200).send('ignored'); return; } try { const [{ MercadoPagoProvider }, { PaymentWebhookService, verifyMercadoPagoWebhook }] = await Promise.all([loadMercadoPagoProvider(), loadWebhookService()]); const dataId = typeof request.query['data.id'] === 'string' ? request.query['data.id'] : typeof request.body?.data?.id === 'string' || typeof request.body?.data?.id === 'number' ? String(request.body.data.id) : undefined; const requestId = request.get('x-request-id') ?? undefined; const providerEventId = typeof request.body?.id === 'string' || typeof request.body?.id === 'number' ? String(request.body.id) : undefined; verifyMercadoPagoWebhook({ xSignature: request.get('x-signature') ?? undefined, xRequestId: requestId, dataId, secret: MERCADO_PAGO_ORDERS_WEBHOOK_SECRET.value() }); if (!dataId || !requestId || !providerEventId) { response.status(400).send('invalid-notification'); return; } await new PaymentWebhookService(adminDb, new MercadoPagoProvider(MERCADO_PAGO_ORDERS_ACCESS_TOKEN.value())).process(dataId, providerEventId, requestId); response.status(200).send('ok'); } catch (error) { const status = error instanceof AppError && error.code === 'permission-denied' ? 401 : 500; response.status(status).send(status === 401 ? 'unauthorized' : 'internal-error'); } });
