import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
const state = vi.hoisted(() => ({ config: { name: 'Agência Teste', logoUrl: 'https://old.test/logo.png', phone: '', email: '', socialLinks: {} }, save: vi.fn(), setConfig: vi.fn(), feedback: { success: vi.fn(), error: vi.fn() } }));
const storage = vi.hoisted(() => ({ createStorageReference: vi.fn((path: string) => ({ path })), uploadFile: vi.fn(), getFileDownloadUrl: vi.fn() }));
vi.mock('../hooks', () => ({ useAgencyConfig: () => ({ config: state.config, setConfig: state.setConfig, loading: false, save: state.save }), useFeedback: () => state.feedback }));
vi.mock('../data/repositories', () => storage);
import AgencySettings from '../components/Admin/AgencySettings';

describe('logo nas configurações da agência', () => {
  beforeEach(() => { vi.clearAllMocks(); state.config = { name: 'Agência Teste', logoUrl: 'https://old.test/logo.png', phone: '', email: '', socialLinks: {} }; state.setConfig.mockImplementation(next => { state.config = next; }); state.save.mockResolvedValue(undefined); storage.uploadFile.mockReturnValue({ completion: Promise.resolve({ path: 'uploaded' }) }); storage.getFileDownloadUrl.mockResolvedValue('https://new.test/logo.png'); vi.stubGlobal('URL', { ...URL, createObjectURL: vi.fn(() => 'blob:preview'), revokeObjectURL: vi.fn() }); });
  afterEach(() => vi.unstubAllGlobals());
  it('aceita imagem, usa o caminho lógico e persiste logoUrl', async () => { render(<AgencySettings />); fireEvent.change(screen.getByLabelText('Selecionar logotipo da agência'), { target: { files: [new File(['png'], 'logo.png', { type: 'image/png' })] } }); expect(screen.getByAltText('Logotipo atual da agência')).toHaveAttribute('src', 'blob:preview'); await waitFor(() => expect(state.save).toHaveBeenCalledWith(expect.objectContaining({ logoUrl: 'https://new.test/logo.png' }))); expect(storage.createStorageReference.mock.calls[0][0]).toMatch(/^agency\/logo\/logo-\d+\.png$/); });
  it('rejeita arquivo maior que 5 MB e formato inválido', () => { render(<AgencySettings />); const large = new File(['x'], 'grande.png', { type: 'image/png' }); Object.defineProperty(large, 'size', { value: 5 * 1024 * 1024 + 1 }); const input = screen.getByLabelText('Selecionar logotipo da agência'); fireEvent.change(input, { target: { files: [large] } }); fireEvent.change(input, { target: { files: [new File(['x'], 'logo.gif', { type: 'image/gif' })] } }); expect(state.feedback.error).toHaveBeenCalledWith(expect.stringMatching(/5 MB/)); expect(state.feedback.error).toHaveBeenCalledWith(expect.stringMatching(/Formato inválido/)); expect(storage.uploadFile).not.toHaveBeenCalled(); });
  it('mantém o logo anterior quando o upload falha', async () => { storage.uploadFile.mockReturnValue({ completion: Promise.reject(new Error('falha')) }); render(<AgencySettings />); fireEvent.change(screen.getByLabelText('Selecionar logotipo da agência'), { target: { files: [new File(['x'], 'logo.webp', { type: 'image/webp' })] } }); await waitFor(() => expect(state.feedback.error).toHaveBeenCalledWith(expect.stringMatching(/anterior foi mantido/))); expect(screen.getByAltText('Logotipo atual da agência')).toHaveAttribute('src', 'https://old.test/logo.png'); expect(state.save).not.toHaveBeenCalled(); });
});
