import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import ClientDialog from '../components/Admin/ClientDialog';
import AccessConfirmationDialog from '../components/Admin/AccessConfirmationDialog';

describe('cadastro completo de cliente', () => {
  it('cria Brand sem acesso sem incluir senha', async () => { const save = vi.fn().mockResolvedValue(undefined); render(<ClientDialog processing={false} onClose={vi.fn()} onSave={save} />); fireEvent.change(screen.getByLabelText('Nome da empresa / marca'), { target: { value: 'Marca A' } }); fireEvent.click(screen.getByRole('button', { name: 'Criar cliente' })); await waitFor(() => expect(save).toHaveBeenCalledWith(expect.objectContaining({ createAccess: false, brand: expect.objectContaining({ name: 'Marca A' }) }))); expect(save.mock.calls[0][0]).not.toHaveProperty('password'); });
  it('valida e envia acesso somente no estado temporário', async () => { const save = vi.fn().mockResolvedValue(undefined); render(<ClientDialog processing={false} onClose={vi.fn()} onSave={save} />); fireEvent.change(screen.getByLabelText('Nome da empresa / marca'), { target: { value: 'Marca A' } }); fireEvent.click(screen.getByLabelText('Criar acesso ao portal para este cliente')); fireEvent.change(screen.getByLabelText('E-mail de acesso'), { target: { value: 'CLIENTE@EXEMPLO.COM' } }); fireEvent.change(screen.getByLabelText('Senha inicial'), { target: { value: 'senha123' } }); fireEvent.change(screen.getByLabelText('Confirmar senha'), { target: { value: 'senha123' } }); fireEvent.click(screen.getByRole('button', { name: 'Criar cliente e acesso' })); await waitFor(() => expect(save).toHaveBeenCalledWith(expect.objectContaining({ createAccess: true, accessEmail: 'cliente@exemplo.com', password: 'senha123' }))); expect(save.mock.calls[0][0].brand).not.toHaveProperty('password'); });
  it('mostra e copia dados apenas na confirmação', async () => { const writeText = vi.fn().mockResolvedValue(undefined); Object.assign(navigator, { clipboard: { writeText } }); render(<AccessConfirmationDialog access={{ name: 'Marca A', email: 'c@e.com', password: 'senha123', portalUrl: 'https://portal.exemplo' }} onClose={vi.fn()} />); expect(screen.getByText('senha123')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Copiar mensagem para o cliente' })); expect(writeText).toHaveBeenCalledWith(expect.stringContaining('https://portal.exemplo')); expect(writeText).toHaveBeenCalledWith(expect.stringContaining('senha123')); });
});
