import { beforeEach, describe, expect, it, vi } from 'vitest';
const repo = vi.hoisted(() => ({ subscribeToInvoices: vi.fn(), subscribeToInvoicesByBrand: vi.fn(), subscribeToInvoiceHistory: vi.fn(), getInvoiceById: vi.fn(), createInvoice: vi.fn(), createInvoiceSeries: vi.fn(), updateInvoice: vi.fn(), markInvoicePaid: vi.fn(), suspendInvoice: vi.fn(), resumeInvoice: vi.fn(), cancelInvoice: vi.fn(), replaceInvoiceBoleto: vi.fn(), reviewPaymentPromise: vi.fn(), createNotification: vi.fn(), listAdminUids: vi.fn(), subscribeToNotifications: vi.fn(), subscribeToUnreadCount: vi.fn(), markNotificationAsRead: vi.fn(), markAllNotificationsAsRead: vi.fn() }));
const functions = vi.hoisted(() => ({ callRequestPaymentPromise: vi.fn(), callCreatePaymentIntent: vi.fn() }));
vi.mock('../data/repositories', () => repo); vi.mock('../data/functions', () => functions);
import { approvePaymentPromise, createInvoice, createRecurringInvoices, editInvoice, markPaid, requestPaymentPromise, resumeInvoice } from '../services/invoices.service';
const base = { id: 'i', brandId: 'b', description: 'Mensalidade', amount: 100, dueDate: '2026-01-01', status: 'pending' as const };
describe('invoice service', () => {
  beforeEach(() => { vi.clearAllMocks(); repo.getInvoiceById.mockResolvedValue(base); repo.createInvoice.mockResolvedValue('i'); repo.createInvoiceSeries.mockResolvedValue(['i1','i2','i3','i4']); repo.listAdminUids.mockResolvedValue([]); });
  it('cobrança única continua canônica', async () => { await expect(createInvoice({ brandId: 'b', description: ' Mensalidade ', amount: 100, dueDate: '2026-01-10' }, { actorUid: 'a', actorRole: 'admin' })).resolves.toBe('i'); expect(repo.createInvoice).toHaveBeenCalledWith(expect.objectContaining({ status: 'pending' }), expect.objectContaining({ action: 'created' })); });
  it('cria série com IDs, grupo, valor, Pix e status próprios', async () => { const ids = await createRecurringInvoices({ brandId: 'b', description: 'Mensalidade', amount: 1200, pixKey: 'pix-123', recurrence: { start: '2026-09', end: '2026-12', day: 10 } }, { actorUid: 'a', actorRole: 'admin' }); expect(new Set(ids).size).toBe(4); const entries = repo.createInvoiceSeries.mock.calls[0][0]; expect(entries).toHaveLength(4); expect(new Set(entries.map((entry: any) => entry.invoice.recurrenceGroupId)).size).toBe(1); expect(entries.every((entry: any) => entry.invoice.amount === 1200 && entry.invoice.pixKey === 'pix-123' && entry.invoice.status === 'pending')).toBe(true); expect(entries.map((entry: any) => entry.invoice.dueDate)).toEqual(['2026-09-10','2026-10-10','2026-11-10','2026-12-10']); });
  it('rejeita valor inválido antes de abrir o batch da série', async () => { await expect(createRecurringInvoices({ brandId: 'b', description: 'Mensalidade', amount: 0, recurrence: { start: '2026-09', end: '2026-12', day: 10 } }, { actorUid: 'a', actorRole: 'admin' })).rejects.toMatchObject({ code: 'invalid-amount' }); expect(repo.createInvoiceSeries).not.toHaveBeenCalled(); });
  it('edita apenas uma cobrança sem campos de série', async () => { await editInvoice('i', { amount: 150 }, { actorUid: 'a', actorRole: 'admin' }); expect(repo.updateInvoice).toHaveBeenCalledWith('i', expect.objectContaining({ amount: 150 }), expect.anything()); expect(repo.updateInvoice.mock.calls[0][1]).not.toHaveProperty('recurrenceGroupId'); });
  it('marca paga individualmente', async () => { await markPaid('i', { actorUid: 'a', actorRole: 'admin' }); expect(repo.markInvoicePaid).toHaveBeenCalledWith('i', expect.anything()); await expect(resumeInvoice('i', { actorUid: 'a', actorRole: 'admin' })).rejects.toMatchObject({ code: 'invalid-transition' }); });
  it('preserva promessa do cliente', async () => { await requestPaymentPromise('i', '2026-01-10', 'Pagarei dia 10', { actorUid: 'b', actorRole: 'client' }, new Date('2026-01-05T12:00:00Z')); expect(functions.callRequestPaymentPromise).toHaveBeenCalled(); repo.getInvoiceById.mockResolvedValue({ ...base, paymentPromise: { requestedDate: '2026-01-10', reason: 'R', status: 'pending' } }); await approvePaymentPromise('i', { actorUid: 'a', actorRole: 'admin' }); expect(repo.reviewPaymentPromise).toHaveBeenCalled(); });
});
