import { beforeEach, describe, expect, it, vi } from 'vitest';
const sdk = vi.hoisted(() => ({ collection: vi.fn((_db, path) => ({ path })), doc: vi.fn((...args) => ({ path: args.slice(1).join('/'), id: args.at(-1) ?? 'generated' })), documentId: vi.fn(() => '__name__'), query: vi.fn((...args) => args), where: vi.fn((...args) => ['where', ...args]), orderBy: vi.fn((...args) => ['orderBy', ...args]), limit: vi.fn((value) => ['limit', value]), startAfter: vi.fn(value => ['startAfter', value]), serverTimestamp: vi.fn(() => 'NOW'), setDoc: vi.fn(), updateDoc: vi.fn(), deleteDoc: vi.fn(), getDoc: vi.fn(), getDocs: vi.fn() }));
const helpers = vi.hoisted(() => ({ subscribeToQuery: vi.fn(() => vi.fn()), normalizeFirestoreError: vi.fn(() => new Error('normalizado')), removeUndefined: (record: Record<string, unknown>) => Object.fromEntries(Object.entries(record).filter(([, value]) => value !== undefined)) }));
vi.mock('firebase/firestore', () => ({ ...sdk, Timestamp: class Timestamp {} })); vi.mock('../lib/firebase', () => ({ db: {} })); vi.mock('../data/firebase', () => helpers);
import { createMediaRecord, getMediaByIds, listMediaPage, markMediaDeleted, permanentlyDeleteMediaRecord, restoreMedia, subscribeToMediaByBrand, updateMediaMetadata } from '../data/repositories/media.repository';

describe('media repository', () => {
  beforeEach(() => { vi.clearAllMocks(); sdk.setDoc.mockResolvedValue(undefined); sdk.updateDoc.mockResolvedValue(undefined); sdk.deleteDoc.mockResolvedValue(undefined); });
  it('sempre consulta por brandId e retorna unsubscribe', () => { const unsubscribe = vi.fn(); helpers.subscribeToQuery.mockReturnValue(unsubscribe); expect(subscribeToMediaByBrand('b', vi.fn(), vi.fn())).toBe(unsubscribe); expect(sdk.where).toHaveBeenCalledWith('brandId', '==', 'b'); });
  it('cria sem persistir ID e atualiza metadados', async () => { await expect(createMediaRecord({ brandId: 'b', status: 'pending', ignored: undefined } as never, 'm')).resolves.toBe('m'); expect(sdk.setDoc).toHaveBeenCalledWith(expect.anything(), expect.not.objectContaining({ id: expect.anything(), ignored: expect.anything() })); await updateMediaMetadata('b', 'm', { status: 'ready' }); expect(sdk.updateDoc).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ brandId: 'b', status: 'ready' })); });
  it('faz delete lógico, restore e delete permanente protegido por marca', async () => { await markMediaDeleted('b', 'm'); await restoreMedia('b', 'm'); sdk.getDoc.mockResolvedValue({ exists: () => true, id: 'm', data: () => ({ brandId: 'b', storagePath: 'x' }) }); await permanentlyDeleteMediaRecord('b', 'm'); expect(sdk.deleteDoc).toHaveBeenCalled(); });
  it('normaliza erros', async () => { sdk.setDoc.mockRejectedValueOnce(new Error('raw')); await expect(createMediaRecord({} as never)).rejects.toThrow('normalizado'); });
  it('lista página limitada, filtrada por marca e sem expor snapshot', async () => { const docs = Array.from({ length: 25 }, (_, index) => ({ id: `m${index}`, data: () => ({ brandId: 'b', mediaType: 'image', status: 'ready' }) })); sdk.getDocs.mockResolvedValue({ docs }); const result = await listMediaPage({ brandId: 'b', type: 'image', status: 'ready' }); expect(sdk.where).toHaveBeenCalledWith('brandId', '==', 'b'); expect(sdk.limit).toHaveBeenCalledWith(25); expect(result.items).toHaveLength(24); expect(result.hasMore).toBe(true); expect(result.nextCursor).toBe('m23'); });
  it('busca IDs em chunks sem subscriptions individuais', async () => { sdk.getDocs.mockResolvedValue({ docs: [] }); await getMediaByIds(Array.from({ length: 11 }, (_, index) => `m${index}`)); expect(sdk.getDocs).toHaveBeenCalledTimes(2); expect(sdk.where).toHaveBeenCalledWith('__name__', 'in', expect.any(Array)); });
});
