import { fireEvent, render, screen } from '@testing-library/react'; import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { Invoice } from '../types'; import type { Payment } from '../payments'; import { canPayInvoiceWithPix, isPixPastDisplayedExpiry } from '../payments'; import PixPaymentView from '../components/finance/PixPaymentView';
const callable = vi.hoisted(() => vi.fn()); const httpsCallable = vi.hoisted(() => vi.fn(() => callable));
vi.mock('firebase/functions', () => ({ connectFunctionsEmulator: vi.fn(), getFunctions: vi.fn(() => ({})), httpsCallable })); vi.mock('../lib/firebase', () => ({ app: {}, usingFirebaseEmulators: false }));
import { callCreatePixPayment } from '../data/functions';
const invoice = (status: Invoice['status']): Invoice => ({ id: 'i', brandId: 'b', amount: 10.55, dueDate: '2026-08-01', status, description: 'Mensalidade' });
const payment = (status: Payment['status']): Payment => ({ id: 'p', invoiceId: 'i', brandId: 'b', provider: 'mercado_pago', method: 'pix', status, amountCents: 1055, currency: 'BRL', externalReference: 'i/p', idempotencyKey: '550e8400-e29b-41d4-a716-446655440000', pix: { copyPasteCode: 'pix-code', qrCodeImage: 'base64' }, expiresAt: new Date('2026-08-10T20:00:00Z') });
describe('checkout Pix', () => {
  beforeEach(() => vi.clearAllMocks());
  it('envia somente invoice e idempotência para callable', async () => { callable.mockResolvedValue({ data: { paymentId: 'p', invoiceId: 'i', status: 'pending', amountCents: 1055, currency: 'BRL', pix: { copyPasteCode: 'code', expiresAt: '2026-08-10T20:00:00Z' } } }); await callCreatePixPayment('i', '550e8400-e29b-41d4-a716-446655440000'); expect(httpsCallable).toHaveBeenCalledWith(expect.anything(), 'createPixPayment'); expect(callable).toHaveBeenCalledWith({ invoiceId: 'i', idempotencyKey: '550e8400-e29b-41d4-a716-446655440000' }); });
  it('Pagar agora só é elegível em pending/overdue', () => { expect(canPayInvoiceWithPix(invoice('pending'))).toBe(true); expect(canPayInvoiceWithPix(invoice('overdue'))).toBe(true); expect(canPayInvoiceWithPix(invoice('paid'))).toBe(false); expect(canPayInvoiceWithPix(invoice('cancelled'))).toBe(false); expect(canPayInvoiceWithPix(invoice('suspended'))).toBe(false); });
  it('expiração visual não promove status financeiro no browser', () => { expect(isPixPastDisplayedExpiry(payment('pending'), new Date('2026-08-11T00:00:00Z'))).toBe(true); expect(isPixPastDisplayedExpiry(payment('approved'), new Date('2026-08-11T00:00:00Z'))).toBe(false); });
  it('mostra QR, copiar, pending, approved e retry expirado', () => { const copy = vi.fn(); const retry = vi.fn(); const view = render(<PixPaymentView invoice={invoice('overdue')} payment={payment('pending')} creating={false} onCreate={vi.fn()} onRetry={retry} onCopy={copy} onBack={vi.fn()} />); expect(screen.getByText('Aguardando pagamento')).toBeInTheDocument(); expect(screen.getByAltText('QR Code Pix')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: /copiar código/i })); expect(copy).toHaveBeenCalled(); view.rerender(<PixPaymentView invoice={invoice('paid')} payment={payment('approved')} creating={false} onCreate={vi.fn()} onRetry={retry} onCopy={copy} onBack={vi.fn()} />); expect(screen.getByText('Pagamento confirmado')).toBeInTheDocument(); view.rerender(<PixPaymentView invoice={invoice('overdue')} payment={payment('expired')} creating={false} onCreate={vi.fn()} onRetry={retry} onCopy={copy} onBack={vi.fn()} />); fireEvent.click(screen.getByRole('button', { name: /gerar novo pix/i })); expect(retry).toHaveBeenCalled(); });
});
