import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
const service = vi.hoisted(() => ({ loadMediaByIds: vi.fn(), prepareMediaUpload: vi.fn(), startPreparedMediaUpload: vi.fn(), failUpload: false }));
vi.mock('../services/media.service', () => service);
vi.mock('../components/media/MediaPicker', () => ({ default: ({ onConfirm, onCancel }: { onConfirm: (ids: string[]) => void; onCancel: () => void }) => <div><button onClick={() => onConfirm(['m1', 'm2', 'm3'])}>Escolher três</button><button onClick={onCancel}>Cancelar picker</button></div> }));
import PostModal from '../components/Admin/PostModal';
const assets = ['m1', 'm2', 'm3'].map((id, index) => ({ id, brandId: 'b', originalFileName: `Mídia ${index + 1}`, mediaType: index === 2 ? 'video' : 'image', downloadUrl: `https://example.test/${id}` }));

describe('PostModal media integration', () => {
  beforeEach(() => {
    service.failUpload = false;
    vi.stubGlobal('URL', { ...URL, createObjectURL: vi.fn(() => 'blob:preview'), revokeObjectURL: vi.fn() });
    service.loadMediaByIds.mockImplementation(async (ids: string[] = []) => assets.filter(asset => ids.includes(asset.id)).concat(ids.filter(id => !assets.some(asset => asset.id === id)).map(id => ({ id, brandId: 'b', originalFileName: 'upload.jpg', mediaType: 'image', downloadUrl: 'https://example.test/upload.jpg' }))));
    service.prepareMediaUpload.mockImplementation((brandId: string, file: File, category: string, mediaId: string) => ({ mediaId, storagePath: `brands/${brandId}/media/${mediaId}/${file.name}`, record: { brandId, originalFileName: file.name, mediaType: 'image', category } }));
    service.startPreparedMediaUpload.mockImplementation((prepared: { mediaId: string }) => ({ mediaId: prepared.mediaId, cancel: vi.fn(() => true), completion: service.failUpload ? Promise.reject(new Error('Falha no upload')) : Promise.resolve({ id: prepared.mediaId }) }));
  });
  afterEach(() => vi.unstubAllGlobals());
  it('seleciona, remove, ordena, define capa e salva', async () => { const save = vi.fn(); render(<PostModal brandId="b" onClose={vi.fn()} onSave={save} />); fireEvent.click(screen.getByRole('button', { name: /selecionar da biblioteca/i })); fireEvent.click(screen.getByText('Escolher três')); await screen.findByText(/Mídia 1/); fireEvent.click(screen.getByRole('button', { name: 'Mover 2 para esquerda' })); fireEvent.click(screen.getByRole('button', { name: 'Definir mídia 3 como capa' })); fireEvent.click(screen.getByRole('button', { name: 'Remover mídia 2' })); fireEvent.click(screen.getByRole('button', { name: 'Criar post' })); await waitFor(() => expect(save).toHaveBeenCalled()); const payload = save.mock.calls[0][0]; expect(payload.brandId).toBe('b'); expect(payload.mediaIds).toEqual(['m2', 'm3']); expect(payload.coverMediaId).toBe('m3'); });
  it('carrega seleção, ordem e capa ao editar', async () => { render(<PostModal brandId="b" post={{ id: 'p', brandId: 'b', type: 'feed', socialNetwork: 'instagram', caption: '', scheduledDate: new Date().toISOString(), status: 'pending', mediaIds: ['m2', 'm1'], coverMediaId: 'm1' }} onClose={vi.fn()} onSave={vi.fn()} />); await screen.findByText(/1\. Mídia 2/); expect(screen.getByText('Capa do post')).toBeInTheDocument(); });
  it('preserva preview legado enquanto não substituído', () => { render(<PostModal brandId="b" post={{ id: 'p', brandId: 'b', type: 'feed', socialNetwork: 'instagram', caption: '', scheduledDate: new Date().toISOString(), status: 'pending', mediaUrl: 'https://example.test/legacy.jpg' }} onClose={vi.fn()} onSave={vi.fn()} />); expect(screen.getByText('Mídia legada preservada')).toBeInTheDocument(); expect(screen.getByAltText('Mídia legada 1')).toBeInTheDocument(); });
  it('faz upload uma vez, registra a mídia e vincula o mediaId ao post', async () => { const save = vi.fn(); render(<PostModal brandId="b" onClose={vi.fn()} onSave={save} />); const file = new File(['x'], 'upload.jpg', { type: 'image/jpeg' }); fireEvent.change(screen.getByLabelText('Arquivos para o post'), { target: { files: [file] } }); await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Concluído')); fireEvent.click(screen.getByRole('button', { name: 'Criar post' })); await waitFor(() => expect(save).toHaveBeenCalled()); expect(service.startPreparedMediaUpload).toHaveBeenCalledTimes(1); expect(save.mock.calls[0][0].mediaIds).toHaveLength(1); });
  it('não duplica o mesmo arquivo na mesma operação', async () => { render(<PostModal brandId="b" onClose={vi.fn()} onSave={vi.fn()} />); const file = new File(['x'], 'igual.jpg', { type: 'image/jpeg', lastModified: 10 }); const input = screen.getByLabelText('Arquivos para o post'); fireEvent.change(input, { target: { files: [file, file] } }); await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Concluído')); expect(service.startPreparedMediaUpload).toHaveBeenCalledTimes(1); });
  it('falha de upload mantém o modal e impede criar post inválido', async () => { service.failUpload = true; const save = vi.fn(); render(<PostModal brandId="b" onClose={vi.fn()} onSave={save} />); fireEvent.change(screen.getByLabelText('Arquivos para o post'), { target: { files: [new File(['x'], 'falha.jpg', { type: 'image/jpeg' })] } }); await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Falhou')); expect(screen.getByRole('button', { name: 'Criar post' })).toBeDisabled(); expect(save).not.toHaveBeenCalled(); });
});
