import { Copy, QrCode } from 'lucide-react';
import { formatCurrencyBRL } from '../../invoices';
import { isPixPastDisplayedExpiry, type Payment, type PaymentStatus } from '../../payments';
import type { Invoice } from '../../types';
const labels: Record<PaymentStatus, string> = { created: 'Pronto para gerar', pending: 'Aguardando pagamento', processing: 'Processando pagamento', approved: 'Pagamento confirmado', rejected: 'Pagamento não aprovado', expired: 'Pix expirado', cancelled: 'Pagamento cancelado', refunded: 'Pagamento estornado' };
type Props = { invoice: Invoice; payment: Payment | null; creating: boolean; onCreate: () => void; onRetry: () => void; onCopy: () => void; onBack: () => void };
export default function PixPaymentView({ invoice, payment, creating, onCreate, onRetry, onCopy, onBack }: Props) {
  const status = payment?.status ?? 'created'; const pastDisplayedExpiry = payment ? isPixPastDisplayedExpiry(payment) : false; const image = payment?.pix?.qrCodeImage; const imageSource = image ? (image.startsWith('data:image/') ? image : `data:image/png;base64,${image}`) : undefined;
  return <section className="mx-auto max-w-2xl rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><QrCode className="h-7 w-7" /><div><p className="text-sm text-zinc-500">Pagamento via Pix</p><h1 className="text-2xl font-extrabold">{formatCurrencyBRL(invoice.amount)}</h1></div></div><p className="mt-3 text-sm text-zinc-600">{invoice.description || 'Fatura'}</p><div className="mt-6 rounded-2xl bg-zinc-50 p-5 text-center"><strong className={status === 'approved' ? 'text-green-700' : status === 'expired' || status === 'rejected' ? 'text-red-700' : 'text-orange-700'}>{labels[status]}</strong>{imageSource && status !== 'approved' && <img src={imageSource} alt="QR Code Pix" className="mx-auto mt-5 h-64 w-64 rounded-xl bg-white object-contain p-2" />}{payment?.pix?.copyPasteCode && status !== 'approved' && <><label className="mt-5 block text-left text-sm font-bold">Pix Copia e Cola<textarea readOnly value={payment.pix.copyPasteCode} rows={4} className="mt-2 w-full resize-none rounded-xl border bg-white p-3 font-mono text-xs" /></label><button onClick={onCopy} className="mt-3 min-h-11 rounded-xl bg-black px-5 font-bold text-white"><Copy className="mr-2 inline h-4 w-4" />Copiar código</button></>}{payment?.expiresAt && status === 'pending' && <p className="mt-4 text-xs text-zinc-500">Expira em {payment.expiresAt.toLocaleString('pt-BR')}</p>}{pastDisplayedExpiry && <p className="mt-2 text-xs text-orange-700">O horário informado encerrou. Aguardando confirmação segura do provedor.</p>}{status === 'approved' && <p className="mt-4 text-sm text-green-700">A fatura será atualizada automaticamente.</p>}{status === 'expired' && <><p className="mt-3 text-sm">Este Pix expirou.</p><button disabled={creating} onClick={onRetry} className="mt-4 min-h-11 rounded-xl bg-black px-5 font-bold text-white">{creating ? 'Gerando...' : 'Gerar novo Pix'}</button></>}{status === 'rejected' && <button disabled={creating} onClick={onRetry} className="mt-4 min-h-11 rounded-xl bg-black px-5 font-bold text-white">Tentar novamente</button>}{status === 'created' && <button disabled={creating} onClick={onCreate} className="mt-5 min-h-11 rounded-xl bg-black px-6 font-bold text-white">{creating ? 'Gerando Pix...' : 'Gerar Pix'}</button>}</div><button onClick={onBack} className="mt-5 min-h-11 rounded-xl border px-5 font-bold">Voltar ao financeiro</button></section>;
}
