import type { Invoice, InvoiceHistory, InvoiceStatus, PaymentPromise, UserRole } from '../types';
import * as repository from '../data/repositories';
import { assertInvoiceTransition, getEffectiveInvoiceStatus, validateCivilDate, validateInvoiceAmount, validatePaymentPromise, validatePixLink } from '../invoices';
import { notifyInvoiceCreated, notifyPaymentConfirmed, notifyPaymentPromiseApproved, notifyPaymentPromiseRejected } from './notifications.service';
import { callRequestPaymentPromise } from '../data/functions';
export const watchInvoices = repository.subscribeToInvoices; export const watchBrandInvoices = repository.subscribeToInvoicesByBrand; export const watchInvoiceHistory = repository.subscribeToInvoiceHistory;
export interface InvoiceActor { actorUid: string; actorRole: UserRole; }
const history = (invoice: Pick<Invoice, 'id' | 'brandId'>, action: InvoiceHistory['action'], actor: InvoiceActor, extra: Partial<InvoiceHistory> = {}): Omit<InvoiceHistory, 'id' | 'createdAt'> => ({ invoiceId: invoice.id, brandId: invoice.brandId, action, actorUid: actor.actorUid, actorRole: actor.actorRole, ...extra });
const requireInvoice = async (id: string) => { const item = await repository.getInvoiceById(id); if (!item) throw new Error('Fatura não encontrada.'); return item; };
export async function createInvoice(data: Pick<Invoice, 'brandId' | 'description' | 'amount' | 'dueDate'> & Partial<Invoice>, actor: InvoiceActor) { if (actor.actorRole !== 'admin' || !actor.actorUid || !data.brandId || !data.description?.trim()) throw new Error('Dados inválidos.'); validateInvoiceAmount(data.amount); validateCivilDate(data.dueDate); validatePixLink(data.boletoUrl); const invoice: Omit<Invoice, 'id' | 'createdAt' | 'updatedAt'> = { brandId: data.brandId, description: data.description.trim(), notes: data.notes?.trim(), amount: data.amount, currency: 'BRL', referenceMonth: data.referenceMonth, originalDueDate: data.dueDate, dueDate: data.dueDate, status: 'pending', boletoMediaId: data.boletoMediaId, boletoUrl: data.boletoUrl, pixKey: data.pixKey, pixKeyType: data.pixKey ? data.pixKeyType : undefined, createdBy: actor.actorUid }; const id = await repository.createInvoice(invoice, { invoiceId: '', brandId: data.brandId, action: 'created', actorUid: actor.actorUid, actorRole: actor.actorRole, newStatus: 'pending', newAmount: data.amount, newDueDate: data.dueDate }); try { await notifyInvoiceCreated(data.brandId, id); } catch { /* notificação não bloqueia a fatura */ } return id; }
export async function editInvoice(id: string, changes: Partial<Invoice>, actor: InvoiceActor) { if (actor.actorRole !== 'admin') throw new Error('Acesso negado.'); const current = await requireInvoice(id); if (changes.brandId && changes.brandId !== current.brandId) throw new Error('Cliente não pode ser alterado.'); if (changes.amount !== undefined) validateInvoiceAmount(changes.amount); if (changes.dueDate) validateCivilDate(changes.dueDate); validatePixLink(changes.boletoUrl); const editable: Partial<Invoice> = { updatedBy: actor.actorUid }; if ('description' in changes) editable.description = changes.description?.trim(); if ('notes' in changes) editable.notes = changes.notes?.trim(); if ('amount' in changes) editable.amount = changes.amount; if ('dueDate' in changes) editable.dueDate = changes.dueDate; if ('referenceMonth' in changes) editable.referenceMonth = changes.referenceMonth; if ('pixKey' in changes) editable.pixKey = changes.pixKey; if ('pixKeyType' in changes) editable.pixKeyType = changes.pixKey ? changes.pixKeyType : undefined; if ('boletoUrl' in changes) editable.boletoUrl = changes.boletoUrl; const action = changes.amount !== undefined && changes.amount !== current.amount ? 'amount_changed' : changes.dueDate && changes.dueDate !== current.dueDate ? 'due_date_changed' : 'edited'; return repository.updateInvoice(id, editable, history(current, action, actor, { previousAmount: current.amount, newAmount: changes.amount, previousDueDate: current.dueDate, newDueDate: changes.dueDate })); }
async function transition(id: string, next: InvoiceStatus, action: InvoiceHistory['action'], actor: InvoiceActor) { if (actor.actorRole !== 'admin') throw new Error('Acesso negado.'); const current = await requireInvoice(id); assertInvoiceTransition(getEffectiveInvoiceStatus(current), next); const record = history(current, action, actor, { previousStatus: getEffectiveInvoiceStatus(current), newStatus: next }); if (next === 'paid') { await repository.markInvoicePaid(id, record); try { await notifyPaymentConfirmed(current.brandId, id); } catch {} } else if (next === 'suspended') await repository.suspendInvoice(id, record); else if (next === 'cancelled') await repository.cancelInvoice(id, record); else await repository.resumeInvoice(id, record); }
export const markPaid = (id: string, actor: InvoiceActor) => transition(id, 'paid', 'marked_paid', actor); export const suspendInvoice = (id: string, actor: InvoiceActor) => transition(id, 'suspended', 'suspended', actor); export const resumeInvoice = (id: string, actor: InvoiceActor) => transition(id, 'pending', 'resumed', actor); export const cancelInvoice = (id: string, actor: InvoiceActor) => transition(id, 'cancelled', 'cancelled', actor);
export async function replaceBoleto(id: string, mediaId: string, actor: InvoiceActor) { const current = await requireInvoice(id); if (actor.actorRole !== 'admin' || !mediaId) throw new Error('Boleto inválido.'); return repository.replaceInvoiceBoleto(id, mediaId, history(current, 'boleto_replaced', actor, { previousBoletoMediaId: current.boletoMediaId, newBoletoMediaId: mediaId })); }
export async function requestPaymentPromise(id: string, requestedDate: string, reason: string, actor: InvoiceActor, now = new Date()) { const current = await requireInvoice(id); if (actor.actorRole !== 'client' || actor.actorUid !== current.brandId) throw new Error('Acesso negado.'); const promise = validatePaymentPromise(current, requestedDate, reason, now); await callRequestPaymentPromise(id, promise.requestedDate!, promise.reason!); }
export async function approvePaymentPromise(id: string, actor: InvoiceActor) { const current = await requireInvoice(id); const promise = current.paymentPromise; if (actor.actorRole !== 'admin' || !promise?.requestedDate || promise.status !== 'pending') throw new Error('Promessa inválida.'); const reviewed: PaymentPromise = { ...promise, status: 'approved', reviewedBy: actor.actorUid }; await repository.reviewPaymentPromise(id, reviewed, promise.requestedDate, history(current, 'payment_promise_approved', actor)); try { await notifyPaymentPromiseApproved(current.brandId, id); } catch {} }
export async function rejectPaymentPromise(id: string, note: string, actor: InvoiceActor) { const current = await requireInvoice(id); const promise = current.paymentPromise; if (actor.actorRole !== 'admin' || !promise || promise.status !== 'pending' || note.trim().length < 3) throw new Error('Promessa inválida.'); const reviewed: PaymentPromise = { ...promise, status: 'rejected', reviewedBy: actor.actorUid, reviewNote: note.trim() }; await repository.reviewPaymentPromise(id, reviewed, undefined, history(current, 'payment_promise_rejected', actor, { note: note.trim() })); try { await notifyPaymentPromiseRejected(current.brandId, id); } catch {} }
