import { useEffect, useState } from 'react';
import type { Brand } from '../../types';
import type { ClientEditableBrandFields } from '../../data/repositories';
import { Save } from 'lucide-react';
import { useBrands, useFeedback } from '../../hooks';

const empty: ClientEditableBrandFields = { name: '', tradeName: '', segment: '', description: '', city: '', state: '', responsible: '', email: '', phone: '', whatsapp: '', website: '', socialLinks: {}, brandColors: '', identityNotes: '', targetAudience: '', mainOffers: '', communicationTone: '', contentNotes: '', avoidedTerms: '', references: '' };
export default function ClientProfile({ brandId }: { brandId: string }) { const [data, setData] = useState<ClientEditableBrandFields>(empty); const { brand, loading, updateClientProfile } = useBrands(brandId); const feedback = useFeedback(); useEffect(() => { if (brand) setData({ ...empty, ...brand, socialLinks: brand.socialLinks ?? {} }); }, [brand]); const set = (key: keyof ClientEditableBrandFields, value: string) => setData(current => ({ ...current, [key]: value })); const social = (key: string, value: string) => setData(current => ({ ...current, socialLinks: { ...current.socialLinks, [key]: value } })); const save = async () => { try { await updateClientProfile(brandId, data); feedback.success('Perfil atualizado com sucesso!'); } catch { feedback.error('Erro ao atualizar perfil.'); } }; if (loading) return <div className="p-20 text-center text-zinc-400">Carregando seus dados...</div>;
  return <div className="max-w-5xl space-y-6"><header className="flex flex-col justify-between gap-4 border-b pb-6 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-bold">Meu Perfil</h1><p className="text-sm text-zinc-500">Complete as informações que ajudam a agência a representar sua marca.</p></div><button onClick={() => void save()} className="min-h-11 rounded-xl bg-black px-5 font-bold text-white"><Save className="mr-2 inline h-4 w-4" />Salvar perfil</button></header><Section title="Empresa / Marca"><Field label="Nome da empresa" value={data.name} onChange={value => set('name', value)} /><Field label="Nome fantasia" value={data.tradeName} onChange={value => set('tradeName', value)} /><Field label="Segmento" value={data.segment} onChange={value => set('segment', value)} /><Field label="Site" value={data.website} onChange={value => set('website', value)} /><Field label="Cidade" value={data.city} onChange={value => set('city', value)} /><Field label="Estado" value={data.state} onChange={value => set('state', value)} /><Area label="Descrição da empresa" value={data.description} onChange={value => set('description', value)} /></Section><Section title="Contatos"><Field label="Responsável" value={data.responsible} onChange={value => set('responsible', value)} /><Field label="E-mail" value={data.email} onChange={value => set('email', value)} /><Field label="Telefone" value={data.phone} onChange={value => set('phone', value)} /><Field label="WhatsApp" value={data.whatsapp} onChange={value => set('whatsapp', value)} /></Section><Section title="Redes sociais">{['instagram','facebook','tiktok','linkedin','youtube'].map(key => <Field key={key} label={key} value={data.socialLinks[key] ?? ''} onChange={value => social(key, value)} />)}</Section><Section title="Identidade / Marca"><Field label="Cores da marca" value={data.brandColors} onChange={value => set('brandColors', value)} /><Area label="Observações de identidade" value={data.identityNotes} onChange={value => set('identityNotes', value)} /></Section><Section title="Informações para conteúdo"><Area label="Público-alvo" value={data.targetAudience} onChange={value => set('targetAudience', value)} /><Area label="Produtos e serviços principais" value={data.mainOffers} onChange={value => set('mainOffers', value)} /><Area label="Tom de comunicação" value={data.communicationTone} onChange={value => set('communicationTone', value)} /><Area label="Observações importantes" value={data.contentNotes} onChange={value => set('contentNotes', value)} /><Area label="Palavras ou expressões a evitar" value={data.avoidedTerms} onChange={value => set('avoidedTerms', value)} /><Area label="Referências" value={data.references} onChange={value => set('references', value)} /></Section>{brand && <section className="rounded-xl bg-zinc-50 p-4 text-sm text-zinc-600"><strong>Dados administrados pela agência:</strong> CNPJ {brand.cnpj || 'não informado'} · Status {brand.status}</section>}</div>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border bg-white p-6"><h2 className="mb-5 text-lg font-bold">{title}</h2><div className="grid gap-5 sm:grid-cols-2">{children}</div></section>; }
function Field({ label, value = '', onChange }: { label: string; value?: string; onChange: (value: string) => void }) { return <label className="text-sm font-bold capitalize">{label}<input value={value} onChange={event => onChange(event.target.value)} className="mt-2 min-h-11 w-full rounded-xl border p-3 font-normal" /></label>; }
function Area({ label, value = '', onChange }: { label: string; value?: string; onChange: (value: string) => void }) { return <label className="text-sm font-bold sm:col-span-2">{label}<textarea value={value} onChange={event => onChange(event.target.value)} rows={3} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label>; }
