export const ROUTES = {
  root: '/',
  login: '/login',
  notFound: '/404',
  admin: {
    root: '/admin',
    clients: '/admin/clientes',
    clientDetail: '/admin/clientes/:brandId',
    clientDetailFor: (brandId: string) => `/admin/clientes/${encodeURIComponent(brandId)}`,
    posts: '/admin/posts',
    calendar: '/admin/calendario',
    finance: '/admin/financeiro',
    metrics: '/admin/metricas',
    trash: '/admin/lixeira',
    settings: '/admin/configuracoes',
    mediaUpload: '/admin/midias/upload',
    media: '/admin/midias',
    notifications: '/admin/notificacoes',
    team: '/admin/equipe',
  },
  client: {
    root: '/cliente',
    posts: '/cliente/posts',
    calendar: '/cliente/calendario',
    finance: '/cliente/financeiro',
    payment: '/cliente/financeiro/:invoiceId/pagar',
    paymentFor: (invoiceId: string) => `/cliente/financeiro/${encodeURIComponent(invoiceId)}/pagar`,
    metrics: '/cliente/metricas',
    profile: '/cliente/perfil',
    showcase: '/cliente/vitrine',
    notifications: '/cliente/notificacoes',
    media: '/cliente/midias',
  },
} as const;
