import { useEffect, useId, useRef, useState, type FormEvent, type KeyboardEvent } from 'react';
import { ArrowLeft, ArrowRight, Calendar, Check, Image, Save, Star, Trash2, X } from 'lucide-react';
import type { MediaAsset } from '../../media';
import type { Brand, Post } from '../../types';
import { loadMediaByIds } from '../../services/media.service';
import { MediaPicker } from '../media';

interface PostModalProps { post?: Post | null; brandId?: string; brands?: Brand[]; initialDate?: string; onClose: () => void; onDelete?: () => void | Promise<void>; onSave: (data: Partial<Post>) => void | Promise<void>; }

export default function PostModal({ post, brandId = '', brands = [], initialDate, onClose, onDelete, onSave }: PostModalProps) {
  const titleId = useId(); const dialogRef = useRef<HTMLDivElement>(null); const previousFocus = useRef<HTMLElement | null>(null);
  const [targetBrandId, setTargetBrandId] = useState(post?.brandId ?? brandId);
  const [formData, setFormData] = useState<Partial<Post>>(post ?? { type: 'feed', socialNetwork: 'instagram', caption: '', scheduledDate: initialDate ?? new Date().toISOString(), status: 'pending' });
  const [selectedIds, setSelectedIds] = useState<string[]>(post?.mediaIds ?? []);
  const [coverMediaId, setCoverMediaId] = useState<string | undefined>(post?.coverMediaId ?? post?.mediaIds?.[0]);
  const [assets, setAssets] = useState<MediaAsset[]>([]); const [pickerOpen, setPickerOpen] = useState(false); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);

  useEffect(() => { let active = true; if (!selectedIds.length) { setAssets([]); return; } loadMediaByIds(selectedIds).then(items => { if (active) setAssets(items); }); return () => { active = false; }; }, [selectedIds]);
  useEffect(() => { previousFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; dialogRef.current?.focus(); return () => { document.body.style.overflow = overflow; previousFocus.current?.focus(); }; }, []);
  useEffect(() => { const escape = (event: globalThis.KeyboardEvent) => { if (event.key === 'Escape' && !pickerOpen) onClose(); }; document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape); }, [onClose, pickerOpen]);
  const trap = (event: KeyboardEvent<HTMLDivElement>) => { if (event.key !== 'Tab') return; const focusable = dialogRef.current?.querySelectorAll<HTMLElement>('button,input,textarea,select,[tabindex]:not([tabindex="-1"])'); if (!focusable?.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
  const choose = (ids: string[]) => { setSelectedIds(ids); setCoverMediaId(current => current && ids.includes(current) ? current : ids[0]); setPickerOpen(false); };
  const remove = (id: string) => { const remaining = selectedIds.filter(value => value !== id); setSelectedIds(remaining); setCoverMediaId(current => current === id ? remaining[0] : current); };
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= selectedIds.length) return; setSelectedIds(current => { const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!targetBrandId) return setError('Selecione um cliente.'); setError(null); setSaving(true); try { await onSave({ ...formData, brandId: targetBrandId, mediaIds: selectedIds, coverMediaId: selectedIds.length ? coverMediaId ?? selectedIds[0] : undefined }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível salvar o post.'); } finally { setSaving(false); } };
  const byId = new Map(assets.map(asset => [asset.id, asset]));
  const legacyUrls = !selectedIds.length ? post?.mediaUrls?.length ? post.mediaUrls : post?.mediaUrl ? [post.mediaUrl] : [] : [];

  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-white/80 p-4 backdrop-blur-xl" onMouseDown={event => { if (event.target === event.currentTarget && !pickerOpen) onClose(); }}>
    <div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby={titleId} tabIndex={-1} onKeyDown={trap} className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-3xl border border-zinc-200 bg-white p-6 shadow-2xl outline-none sm:p-8">
      <header className="mb-8 flex items-center justify-between"><h2 id={titleId} className="text-2xl font-black uppercase tracking-tight">{post ? 'Editar conteúdo' : 'Criar novo post'}</h2><button type="button" onClick={onClose} aria-label="Fechar modal de post" className="rounded-xl p-3 hover:bg-zinc-100"><X className="h-5 w-5" /></button></header>
      <form onSubmit={submit} className="space-y-7">
        {!post && <label className="block text-xs font-bold uppercase tracking-wider text-zinc-500">Cliente<select aria-label="Cliente do post" value={targetBrandId} onChange={event => { setTargetBrandId(event.target.value); setSelectedIds([]); setCoverMediaId(undefined); }} className="mt-2 min-h-12 w-full rounded-xl border border-zinc-300 bg-white px-4 text-sm text-black"><option value="">Selecione</option>{brands.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
        <div className="grid gap-5 sm:grid-cols-2"><label className="text-xs font-bold uppercase tracking-wider text-zinc-500">Plataforma<select aria-label="Rede social" value={formData.socialNetwork} onChange={event => setFormData({ ...formData, socialNetwork: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-zinc-300 bg-white px-4 text-sm text-black"><option value="instagram">Instagram</option><option value="facebook">Facebook</option><option value="tiktok">TikTok</option><option value="linkedin">LinkedIn</option><option value="youtube">YouTube</option></select></label><label className="text-xs font-bold uppercase tracking-wider text-zinc-500">Tipo de post<select aria-label="Formato" value={formData.type} onChange={event => setFormData({ ...formData, type: event.target.value as Post['type'] })} className="mt-2 min-h-12 w-full rounded-xl border border-zinc-300 bg-white px-4 text-sm text-black"><option value="feed">Feed</option><option value="reels">Reels</option><option value="stories">Story</option><option value="carousel">Carrossel</option><option value="other">Outro</option></select></label></div>
        <label className="block text-xs font-bold uppercase tracking-wider text-zinc-500">Objetivo<select value={formData.objective ?? ''} onChange={event => setFormData({ ...formData, objective: event.target.value as Post['objective'] || undefined })} className="mt-2 min-h-12 w-full rounded-xl border border-zinc-300 bg-white px-4 text-sm text-black"><option value="">Não definido</option><option value="venda">Venda</option><option value="engajamento">Engajamento</option><option value="autoridade">Autoridade</option><option value="tráfego">Tráfego</option></select></label>
        <label className="block text-xs font-bold uppercase tracking-wider text-zinc-500">Legenda / descritivo<textarea value={formData.caption ?? ''} onChange={event => setFormData({ ...formData, caption: event.target.value })} rows={5} className="mt-2 w-full resize-none rounded-2xl border border-zinc-300 p-4 text-sm text-black" /></label>
        <label className="block text-xs font-bold uppercase tracking-wider text-zinc-500">Data e hora<div className="relative mt-2"><Calendar className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-400" /><input type="datetime-local" value={formData.scheduledDate?.slice(0, 16) ?? ''} onChange={event => setFormData({ ...formData, scheduledDate: new Date(event.target.value).toISOString() })} className="min-h-12 w-full rounded-xl border border-zinc-300 py-3 pl-11 pr-4 text-sm" /></div></label>
        <label className="block text-xs font-bold uppercase tracking-wider text-zinc-500">Status inicial<select aria-label="Status inicial" value={formData.status} onChange={event => setFormData({ ...formData, status: event.target.value as Post['status'] })} className="mt-2 min-h-12 w-full rounded-xl border border-zinc-300 bg-white px-4"><option value="pending">Pendente</option><option value="scheduled">Agendado</option></select></label>
        <section aria-labelledby="post-media-title" className="rounded-2xl border border-zinc-200 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="post-media-title" className="font-bold">Mídias do post</h3><p className="text-sm text-zinc-500">A ordem abaixo será usada no carrossel.</p></div><button type="button" onClick={() => setPickerOpen(true)} className="min-h-11 rounded-xl bg-black px-4 text-sm font-bold text-white"><Image className="mr-2 inline h-4 w-4" />Selecionar da biblioteca</button></div>
          {selectedIds.length ? <ol className="mt-5 space-y-3">{selectedIds.map((id, index) => { const asset = byId.get(id); const safeUrl = asset?.downloadUrl && /^https?:\/\//i.test(asset.downloadUrl) ? asset.downloadUrl : undefined; return <li key={id} className="flex flex-col gap-3 rounded-xl border border-zinc-200 p-3 sm:flex-row sm:items-center"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-lg bg-zinc-100">{asset?.mediaType === 'image' && safeUrl ? <img src={safeUrl} alt={asset.originalFileName} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-xs text-zinc-500">{asset?.mediaType === 'video' ? 'Vídeo' : 'Mídia'}</div>}</div><div className="min-w-0 flex-1"><p className="truncate font-bold">{index + 1}. {asset?.originalFileName ?? 'Mídia indisponível'}</p><p className="text-xs text-zinc-500">{coverMediaId === id ? 'Capa do post' : asset?.mediaType ?? 'Não encontrada'}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => move(index, -1)} disabled={index === 0} aria-label={`Mover ${index + 1} para esquerda`} className="rounded-lg border p-2 disabled:opacity-30"><ArrowLeft className="h-4 w-4" /></button><button type="button" onClick={() => move(index, 1)} disabled={index === selectedIds.length - 1} aria-label={`Mover ${index + 1} para direita`} className="rounded-lg border p-2 disabled:opacity-30"><ArrowRight className="h-4 w-4" /></button><button type="button" onClick={() => setCoverMediaId(id)} aria-pressed={coverMediaId === id} aria-label={`Definir mídia ${index + 1} como capa`} className={`rounded-lg border p-2 ${coverMediaId === id ? 'bg-black text-white' : ''}`}><Star className="h-4 w-4" /></button><button type="button" onClick={() => remove(id)} aria-label={`Remover mídia ${index + 1}`} className="rounded-lg border border-red-200 p-2 text-red-600"><Trash2 className="h-4 w-4" /></button></div></li>; })}</ol> : legacyUrls.length ? <div className="mt-5"><p className="mb-2 text-sm font-bold text-orange-700">Mídia legada preservada</p><div className="grid grid-cols-2 gap-3">{legacyUrls.map((url, index) => <img key={url} src={url} alt={`Mídia legada ${index + 1}`} className="aspect-square w-full rounded-xl bg-zinc-100 object-contain" />)}</div></div> : <p className="mt-5 rounded-xl bg-zinc-50 p-6 text-center text-sm text-zinc-500">Nenhuma mídia selecionada.</p>}
        </section>
        {error && <p role="alert" className="text-sm font-bold text-red-600">{error}</p>}
        <div className="flex flex-wrap justify-end gap-3 border-t border-zinc-200 pt-6">{post && onDelete && <button type="button" onClick={() => void onDelete()} className="mr-auto min-h-12 rounded-xl border border-red-200 px-6 text-sm font-bold text-red-600"><Trash2 className="mr-2 inline h-4 w-4" />Mover para lixeira</button>}<button type="button" onClick={onClose} className="min-h-12 rounded-xl border border-zinc-300 px-6 text-sm font-bold">Cancelar</button><button type="submit" disabled={saving} className="min-h-12 rounded-xl bg-black px-7 text-sm font-bold text-white disabled:opacity-50"><Save className="mr-2 inline h-4 w-4" />{saving ? 'Salvando...' : post ? 'Salvar alterações' : 'Criar post'}</button></div>
      </form>
    </div>
    {pickerOpen && targetBrandId && <MediaPicker brandId={targetBrandId} selectedIds={selectedIds} onConfirm={choose} onCancel={() => setPickerOpen(false)} />}
  </div>;
}
