import { useEffect, useState, type FormEvent } from 'react'; import type { Brand, TeamMember, TeamRole } from '../../types'; import GlobalModal from '../ui/GlobalModal';
export interface TeamMemberForm { displayName: string; email: string; role: TeamRole; active: boolean; brandIds: string[]; password?: string }
export default function TeamMemberDialog({ member, brands, processing, onClose, onSave }: { member?: TeamMember | null; brands: Brand[]; processing: boolean; onClose: () => void; onSave: (data: TeamMemberForm) => Promise<void> }) {
  const [data, setData] = useState<TeamMemberForm>({ displayName: '', email: '', role: 'social_media', active: true, brandIds: [] }); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (member) setData({ displayName: member.displayName, email: member.email, role: member.role, active: member.active, brandIds: member.brandIds }); }, [member]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!member && (!data.password || data.password.length < 10 || data.password !== confirmation)) return setError('As senhas precisam ser iguais e ter ao menos 10 caracteres.'); setError(''); try { await onSave(data); } catch { setError('Não foi possível salvar o membro. Confira os dados e tente novamente.'); } };
  return <GlobalModal title={member ? 'Editar membro' : 'Novo membro'} size="lg" onClose={onClose} closeOnEscape={!processing} closeOnOverlay={!processing}><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome"><input required disabled={processing} value={data.displayName} onChange={e => setData({ ...data, displayName: e.target.value })} className="input" /></Field><Field label="E-mail"><input required type="email" disabled={Boolean(member) || processing} value={data.email} onChange={e => setData({ ...data, email: e.target.value })} className="input" /></Field><Field label="Função"><select disabled={processing} value={data.role} onChange={e => setData({ ...data, role: e.target.value as TeamRole })} className="input"><option value="manager">Gerente</option><option value="social_media">Social Media</option></select></Field><Field label="Status"><select disabled={processing} value={data.active ? 'active' : 'inactive'} onChange={e => setData({ ...data, active: e.target.value === 'active' })} className="input"><option value="active">Ativo</option><option value="inactive">Inativo</option></select></Field>{!member && <><Field label="Senha inicial"><input required minLength={10} disabled={processing} autoComplete="new-password" type="password" value={data.password ?? ''} onChange={e => setData({ ...data, password: e.target.value })} className="input" /></Field><Field label="Confirmar senha"><input required minLength={10} disabled={processing} autoComplete="new-password" type="password" value={confirmation} onChange={e => setConfirmation(e.target.value)} className="input" /></Field></>}</div><fieldset disabled={processing} className="mt-6"><legend className="font-bold">Clientes atribuídos</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{brands.map(brand => <label key={brand.id} className="flex min-h-11 items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={data.brandIds.includes(brand.id)} onChange={e => setData(current => ({ ...current, brandIds: e.target.checked ? [...current.brandIds, brand.id] : current.brandIds.filter(id => id !== brand.id) }))} />{brand.name}</label>)}</div></fieldset>{error && <p role="alert" className="mt-4 text-sm font-bold text-red-600">{error}</p>}<div className="mt-7 flex justify-end gap-3"><button type="button" disabled={processing} onClick={onClose} className="rounded-xl border px-5 py-3 font-bold">Cancelar</button><button disabled={processing} className="rounded-xl bg-black px-5 py-3 font-bold text-white disabled:opacity-40">{processing ? 'Salvando...' : 'Salvar'}</button></div></form></GlobalModal>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-bold uppercase tracking-wider text-zinc-500">{label}{children}</label>; }
