import test from 'node:test'; import assert from 'node:assert/strict';
import { assertInvoiceAccess, requireAdmin, requireAuthenticatedUid, requireClient, resolveAuthenticatedActor } from '../auth/actor.js'; import { PaymentPromiseService, validatePromiseRequest } from '../invoices/payment-promise.service.js';
const now = new Date('2026-08-10T12:00:00Z'); const invoice = { brandId: 'a', status: 'pending', dueDate: '2026-08-01' };
test('autorização usa actor resolvido e ownership', () => { assert.doesNotThrow(() => requireAdmin({ uid: 'x', role: 'admin' })); assert.doesNotThrow(() => requireClient({ uid: 'a', role: 'client', brandId: 'a' })); assert.doesNotThrow(() => assertInvoiceAccess({ uid: 'a', role: 'client', brandId: 'a' }, invoice)); assert.throws(() => assertInvoiceAccess({ uid: 'b', role: 'client', brandId: 'b' }, invoice)); });
test('callable exige autenticação', () => { assert.equal(requireAuthenticatedUid({ uid: 'a' }), 'a'); assert.throws(() => requireAuthenticatedUid(undefined), (error: { code?: string }) => error.code === 'unauthenticated'); });
test('resolve papel somente por admins/brands confiáveis', async () => { const adminDb = { doc: (path: string) => ({ get: async () => ({ exists: path === 'admins/admin' }) }) }; assert.deepEqual(await resolveAuthenticatedActor(adminDb as never, 'admin'), { uid: 'admin', role: 'admin' }); const clientDb = { doc: (path: string) => ({ get: async () => ({ exists: path === 'brands/client' }) }) }; assert.deepEqual(await resolveAuthenticatedActor(clientDb as never, 'client'), { uid: 'client', role: 'client', brandId: 'client' }); await assert.rejects(resolveAuthenticatedActor({ doc: () => ({ get: async () => ({ exists: false }) }) } as never, 'unknown')); });
test('promise aceita própria overdue dentro dos 15 dias', () => { assert.deepEqual(validatePromiseRequest(invoice, '2026-08-12', 'Pagamento dia 12', now), { requestedDate: '2026-08-12', reason: 'Pagamento dia 12', status: 'pending' }); });
test('promise bloqueia prazo, passado, duplicidade e estados finais', () => { assert.throws(() => validatePromiseRequest(invoice, '2026-08-17', 'Fora do prazo', now)); assert.throws(() => validatePromiseRequest(invoice, '2026-08-09', 'Data passada', now)); assert.throws(() => validatePromiseRequest({ ...invoice, paymentPromise: { status: 'pending' } }, '2026-08-12', 'Duplicada', now)); for (const status of ['paid', 'cancelled', 'suspended']) assert.throws(() => validatePromiseRequest({ ...invoice, status }, '2026-08-12', 'Inválida', now)); });
test('promise backend grava Invoice/history e notifica admins', async () => { const writes: Array<{ kind: string; data: Record<string, unknown> }> = []; const invoiceRef = { collection: () => ({ doc: () => ({ path: 'history/h' }) }) }; const db = { doc: () => invoiceRef, runTransaction: async (work: (transaction: unknown) => Promise<void>) => work({ get: async () => ({ exists: true, data: () => invoice }), update: (_ref: unknown, data: Record<string, unknown>) => writes.push({ kind: 'invoice', data }), create: (_ref: unknown, data: Record<string, unknown>) => writes.push({ kind: 'history', data }) }), collection: (name: string) => name === 'admins' ? { get: async () => ({ docs: [{ id: 'admin-1' }] }) } : { add: async (data: Record<string, unknown>) => { writes.push({ kind: 'notification', data }); return { id: 'n' }; } } }; const result = await new PaymentPromiseService(db as never, () => now).request({ uid: 'a', role: 'client', brandId: 'a' }, { invoiceId: 'i', requestedDate: '2026-08-12', reason: 'Pagamento dia 12' }); assert.deepEqual(result, { invoiceId: 'i', status: 'pending' }); assert.equal(writes.some(item => item.kind === 'history' && item.data.action === 'payment_promise_requested'), true); assert.equal(writes.some(item => item.kind === 'notification' && item.data.recipientUid === 'admin-1'), true); });
