import test from 'node:test';
import assert from 'node:assert/strict';
import { authenticateInternal, hashPassword, normalizeEmail, verifyPassword, type InternalCredential, type LoginDependencies } from '../internal-auth.js';

const credential = async (overrides: Partial<InternalCredential> = {}): Promise<InternalCredential> => ({ uid: 'client-a', emailNormalized: 'cliente@teste.local', role: 'client', active: true, displayName: 'Cliente A', brandId: 'client-a', ...await hashPassword('senha-segura-123'), ...overrides });
const dependencies = (stored: InternalCredential | null, overrides: Partial<LoginDependencies> = {}): LoginDependencies => ({ findCredential: async () => stored, isRateLimited: async () => false, recordFailure: async () => {}, clearFailures: async () => {}, profileExists: async () => true, createCustomToken: async uid => `token:${uid}`, ...overrides });

test('normaliza email e valida scrypt sem armazenar senha', async () => { const data = await credential(); assert.equal(normalizeEmail(' Cliente@Teste.Local '), 'cliente@teste.local'); assert.equal(await verifyPassword('senha-segura-123', data), true); assert.equal(await verifyPassword('incorreta', data), false); assert.equal('password' in data, false); });
test('login cliente retorna token com UID correto e dados públicos mínimos', async () => { const data = await credential(); const result = await authenticateInternal('CLIENTE@TESTE.LOCAL', 'senha-segura-123', dependencies(data)); assert.equal(result.customToken, 'token:client-a'); assert.deepEqual(result.profile, { uid: 'client-a', displayName: 'Cliente A', brandId: 'client-a' }); });
test('login admin válido preserva role e UID', async () => { const data = await credential({ uid: 'admin-a', role: 'admin', brandId: undefined, emailNormalized: 'admin@teste.local' }); const result = await authenticateInternal(data.emailNormalized, 'senha-segura-123', dependencies(data)); assert.equal(result.role, 'admin'); assert.equal(result.profile.uid, 'admin-a'); });
test('senha incorreta registra falha', async () => { let failures = 0; await assert.rejects(authenticateInternal('cliente@teste.local', 'errada', dependencies(await credential(), { recordFailure: async () => { failures += 1; } })), /invalid-credentials/); assert.equal(failures, 1); });
test('email inexistente registra falha', async () => { let failures = 0; await assert.rejects(authenticateInternal('ausente@teste.local', 'qualquer-senha', dependencies(null, { recordFailure: async () => { failures += 1; } })), /invalid-credentials/); assert.equal(failures, 1); });
test('usuário inativo não recebe token', async () => { let failures = 0; await assert.rejects(authenticateInternal('cliente@teste.local', 'senha-segura-123', dependencies(await credential({ active: false }), { recordFailure: async () => { failures += 1; } })), /invalid-credentials/); assert.equal(failures, 1); });
test('rate limit bloqueia antes de validar credencial', async () => { const data = await credential(); await assert.rejects(authenticateInternal(data.emailNormalized, 'senha-segura-123', dependencies(data, { isRateLimited: async () => true })), /invalid-credentials/); });
