export const PAYMENT_PROMISE_REASON_MIN_LENGTH = 3;
export const PAYMENT_PROMISE_REASON_MAX_LENGTH = 500;
export const PAYMENT_PROMISE_MAX_DAYS = 15;
export const INVOICE_DESCRIPTION_MAX_LENGTH = 200;
